#!/bin/sh

cd $HOME/.zsh

echo '#              DO NOT EDIT THIS FILE
# Add your own customizations in ~/.zsh/myconfig.zsh

source ~/.zsh/myconfig.zsh

# Type zshrc to edit config and then type szsh to apply changes' > $HOME/.zshrc

chmod +w $HOME/.oh-my-zsh/custom/

git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting $HOME/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
git clone https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k

echo "Installed the zshrc configuration successfully! Enjoy :-)"
